export enum PermissionSubject {
  'Permission' = 'permission', 
  'Subject' = 'subject', 
  'RolePermission' = 'rolepermission', 
  'Role' = 'role', 
  'User' = 'user', 
  'Staff' = 'staff', 
  'StaffDesignation' = 'staffdesignation', 
  'Attendance' = 'attendance', 
  'Leave' = 'leave', 
  'Customer' = 'customer', 
  'Transaction' = 'transaction', 
  'Vehicle' = 'vehicle', 
  'VehicleBrand' = 'vehiclebrand', 
  'VehicleType' = 'vehicletype', 
  'VehicleWheelerType' = 'vehiclewheelertype', 
  'Service' = 'service', 
}